export const validateForm = (intake) => {
  // validate and throw errors
};
export const defaultForm = {
  name: '',
  firstName: '',
  lastName: '',
  DOB: '',
  address: '',
  city: '',
  state: '',
  zipCode: '',
  homePhone: '',
  mobilePhone: '',
  email: '',
  gender: '',
  employementStatus: '',
  maritalStatus: '',
  companionname: '',
  phone: '',
  guardian: '',
  patientInitial: '',
  primaryPhysician: '',
  primaryPhysicianPhone: '',
  referringPhysician: '',
  referringPhysicianPhone: '',
  referringPhysicianAddress: '',
  resultsent2familydoctor: '',
  referredtobydoctor: '',
  referredtobyfriend: '',
  referredtobynewspaper: '',
  referredtobymailing: '',
  referredtobyother: '',
  hearingtested: '',
  hearingtestedhowlongago: '',
  wearhearingaids: '',
  hearingaidspurchasewhen: '',
  troublehearingrecently: '',
  whosuggestedhearingtest: ''
};
